config/routes.rb
JobSystem::Application.routes.draw do
  get "search/search_results"
  resources :work_orders

  resources :workers

  root 'workers#index'

  

end

app/models/work_order.rb
class WorkOrder < ActiveRecord::Base
  validates_presence_of :details, :status
  
  belongs_to :worker
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  validates_presence_of :last_name, :first_name
  has_many :work_orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search_results
    @work_orders = WorkOrder.where("status = ?", params[:search])
  end
end

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController
  before_action :set_work_order, only: [:show, :edit, :update, :destroy]

  def index
    @status = 'Created'
    @work_orders = WorkOrder.all
  end
  
  def new
    @status = 'Created'
    @work_order = WorkOrder.new
  end
  
  def create
    @work_order = WorkOrder.new(work_order_params)
      if @work_order.save
        redirect_to root_path, :notice => 'Work order was successfully created.'
      else
        render 'new'
    end
  end

  def edit
    @status = 'Created'
    @work_order = WorkOrder.find(params[:id])
  end
  
  def show
    @work_order = WorkOrder.find(params[:id])
    @status = "Details for #{@work_order.status}"
  end

  def update
      if @work_order.update(work_order_params)
       redirect_to root_path, :notice => 'Worker was successfully updated.'
      else
        @title = 'Edit Work Order'
        render 'edit'
    end
  end

  def destroy
    @work_order = WorkOrder.find(params[:id])
    @work_order.destroy
    redirect_to work_orders_path
  end

  private
    def set_work_order
      @work_order = WorkOrder.find(params[:id])
    end

    def work_order_params
      params.require(:work_order).permit(:details, :status, :worker_id)
    end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  def index
    @title = 'Listing workers'
    @workers = Worker.all
  end

  def new
    @title = 'New worker'
    @worker = Worker.new
  end

  def create
    @worker = Worker.new(worker_params)
    if @worker.save
      redirect_to root_path, :notice => 'Worker was successfully created.'
    else
      render 'new'
    end
  end

  def edit
    @title = 'Edit worker'
    @worker = Worker.find(params[:id])
  end

  def show
    @worker = Worker.find(params[:id])
    @title = "Details for #{@worker.first_name}"
  end
  
  def update
    @worker = Worker.find(params[:id])
    if @worker.update(worker_params)
      redirect_to root_path, :notice => 'Worker was successfully updated.'
    else
      @title = 'Edit worker'
      render 'edit'
    end
  end

  def destroy
    @worker = Worker.find(params[:id])
    @worker.destroy
    redirect_to root_path
  end

  private
  
    def worker_params
      params.require(:worker).permit(:last_name, :first_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/search/search_results.html.erb
<h1>Search results</h1>

<% if @work_orders.count > 0 %>
	<table class = "table table-bordered table-striped table table-hover pretty">
	  <thead>
	    <tr>
		  <th>Worker</th>
	      <th>Details</th>
	      <th>Status</th>
	      <th></th>
	      <th></th>
	      <th></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @work_orders.each do |work_order| %>
	      <tr>
			<td><%= work_order.worker_id %></td>
	        <td><%= work_order.details %></td>
	        <td><%= work_order.status %></td>
	        <td><%= link_to 'Show', work_order %></td>
	        <td><%= link_to 'Edit', edit_work_order_path(work_order) %></td>
	        <td><%= link_to 'Destroy', work_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
	
		
		
	<% else %>
	<center><br><h4>No results for your query</h4></center>
<% end %>

<br/>
<%= link_to 'New Work order', new_work_order_path %> | 
<%= link_to 'Back', work_orders_path %>

app/views/work_orders/_form.html.erb
<%= form_for(@work_order) do |f| %>
  <% if @work_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_order.errors.count, "error") %> prohibited this work_order from being saved:</h2>

      <ul>
      <% @work_order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, options_for_select(["created", "in progress", "review", "completed"])%>
	
  </div>
  
  <div class="field">
	  <%= f.label :worker %>
	  <%= f.select :worker_id, Worker.all.map {|worker| [worker.id, worker.id]} %>
  </div>
  
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-primary btn-large"%>
  </div>
<% end %>

app/views/work_orders/edit.html.erb
<title>Edit work order</title>
<h1>Editing work_order</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_order %> |
<%= link_to 'Back', work_orders_path %>

app/views/work_orders/index.html.erb
<title>Listing work orders</title>
<h1>Listing all work orders</h1>

<%= form_tag search_search_results_path, :method => 'get' do %>
	<%= text_field_tag :search, params[:search], :placeholder => 	"Search by status" %>
<% end %>

<br>

<table class = "table table-bordered table-striped table table-hover pretty">
    <tr>
	  <th>Worker</th>
      <th>Details</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <tbody>
    <% @work_orders.each do |work_order| %>
      <tr>
		<td><%= work_order.worker_id %></td>
        <td><%= work_order.details %></td>
        <td><%= work_order.status %></td>
        <td><%= link_to 'Show', work_order %></td>
        <td><%= link_to 'Edit', edit_work_order_path(work_order) %></td>
        <td><%= link_to 'Destroy', work_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work order', new_work_order_path %> | 
<%= link_to 'Workers', workers_path %>

app/views/work_orders/new.html.erb
<title>New worker</title>
<center>
<h1>New work order</h1>

<%= render 'form' %>

<%= link_to 'Back', work_orders_path %>
</center>

app/views/work_orders/show.html.erb
<title>Details for <%= @work_order.status%></title>
<center>
	<h1>Details for work order #<%= @work_order.id %> </h1>
<p id="notice"><%= notice %></p>

<br/>
<br/>

<p>
  <strong>Details:</strong>
  <%= @work_order.details %>
</p>

<p>
  <strong>Status:</strong>
  <%= @work_order.status %>
</p>

<%= link_to 'Edit', edit_work_order_path(@work_order) %> |
<%= link_to 'Back', work_orders_path %>
</center>

app/views/workers/_form.html.erb
<%= form_for(@worker) do |f| %>
  <% if @worker.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@worker.errors.count, 'error') %> prohibited this worker from being saved:</h2>

      <ul>
        <% @worker.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class='field'>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class='field'>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class='actions'>
    <%= f.submit "Submit", :class => "btn btn-primary btn-large" %>
  </div>
<% end %>

app/views/workers/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', '#' %> | <%= link_to 'Back', root_path %>

app/views/workers/index.html.erb
<h1>Listing workers</h1>
<table class = "table table-bordered table-striped table table-hover pretty">
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Work orders</th>
	<th></th>
	<th></th>
	<th></th>
  </tr>

  <% @workers.each do |worker| %>
    <tr>
      <td><%= worker.first_name %></td>
      <td><%= worker.last_name %></td>
      <td><%= link_to 'View all', '#' %></td>
      <td><%= link_to 'Show', worker %></td>
      <td><%= link_to 'Edit', edit_worker_path(worker) %></td>
      <td><%= link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<br />
<%= link_to 'New worker', new_worker_path %> | <%= link_to 'Work Orders', work_orders_path%>

app/views/workers/new.html.erb
<center>
<h1>New worker</h1>

<%= render 'form' %>

<%= link_to 'Back to workers', workers_path %>
</center>

app/views/workers/show.html.erb
<center>
<h1>Details for <%= @worker.first_name %> <%= @worker.last_name %></h1>
<br/><br/>
<h2>Assigned Work Orders</h2>

<table class = "table table-bordered table-striped table table-hover pretty">
    <tr>
	  <th>Worker</th>
      <th>Details</th>
      <th>Status</th>
    </tr>

  <tbody>
    <% @worker.work_orders.each do |worker| %>
      <tr>
  		<td><%= worker.worker_id %></td>
          <td><%= worker.details %></td>
          <td><%= worker.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_worker_path(@worker) %> |
<%= link_to 'Back', root_path %>
</center>